### ISSUE TITLE
How to implement ConvKB on triplet classification

### ISSUE THREAD

**Issue by Tianchen627** [daiquocnguyen/ConvKB#10]
Hi,
I have read your paper of http://www.semantic-web-journal.net/system/files/swj1867.pdf  and found you have implemented ConvKB on the triplet classification task.
I tried to implement it by myself on WN11 dataset but I failed: the model can't fit test set and dev set.I guess the key is about the score function and threshold .
So I would appreciate it if you can  provide the code on the task so that I can find where the mistake is.
Thanks a lot!

**Comment by daiquocnguyen** [comment]
You can see the code for the triple classification at my other new repository: https://github.com/daiquocnguyen/R-MeN
