### ISSUE TITLE
In entity2vec.init, is each line from top to bottom corresponding to the vec of entity id of 0, 1,2,3 etc.?

### ISSUE THREAD

**Issue by namenotexist** [daiquocnguyen/ConvKB#12]
In entity2vec.init, is each line from top to bottom corresponding to the vec of entity id of 0, 1,2,3 etc.?

**Comment by namenotexist** [comment]
I use the same hyperameter setting as yours ,but get hit@10 0.37, what is wrong

**Comment by daiquocnguyen** [comment]
I guess you are talking about running TransE to get the initialization?
