### ISSUE TITLE
no suitable image found.  Did find:

### ISSUE THREAD

**Issue by foreseez** [daiquocnguyen/ConvKB#16]
`python train_ConvKB.py --dataset FB15K237 --hidden_size 100 --num_of_filters 128 --neg_num 10 --valid_step 50 --nbatches 100 --num_epochs 300 --learning_rate 0.01 --lmbda 0.1 --model_name FB15K237_lda-0.1_nneg-10_nfilters-128_lr-0.01 --mode train
Namespace(checkpoint_path=None, dataset='FB15K237', dropout=0.5, hidden_size=100, kernel_size=1, learning_rate=0.01, lmbda=0.1, lmbda2=0.01, mode='train', model_name='FB15K237_lda-0.1_nneg-10_nfilters-128_lr-0.01', nbatches=100, neg_num=10, num_epochs=300, num_of_filters=128, optim='adagrad', save_steps=1000, test_file='', use_init=1, valid_steps=50)
Writing to /Users/***/Downloads/ConvKB-master/runs_pytorch_ConvKB

Traceback (most recent call last):
  File "train_ConvKB.py", line 42, in <module>
    con = Config()
  File "/Users/***/Downloads/ConvKB-master/ConvKB_pytorch/Config.py", line 34, in __init__
    self.lib = ctypes.cdll.LoadLibrary(base_file)
  File "/Users/***/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/Users/***/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/***/Downloads/ConvKB-master/ConvKB_pytorch/release/Base.so, 6): no suitable image found.  Did find:
	/Users/***/Downloads/ConvKB-master/ConvKB_pytorch/release/Base.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/***/Downloads/ConvKB-master/ConvKB_pytorch/release/Base.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00`

- MacOS 
- torch 1.7.0
- when i run the command  get above error  
- why and  how to fix ?

**Comment by daiquocnguyen** [comment]
You should re-run "bash make.sh" to compile the base package.
