### ISSUE TITLE
How to run ConvKB in windows

### ISSUE THREAD

**Issue by SRL94** [daiquocnguyen/ConvKB#17]
ConvKB does not work in windows. Do you have a windows version?

**Comment by daiquocnguyen** [comment]
You can install pytorch and tensorflow via Anaconda to work in Windows OS.

**Comment by SRL94** [comment]
No, the c++ files only work in Linux and Mac.

**Comment by daiquocnguyen** [comment]
The pytorch implementation is based on the [OpenKE framework](https://github.com/thunlp/OpenKE). You can ask them about your issue.

**Comment by Walker-ZD** [comment]
> ConvKB does not work in windows. Do you have a windows version?

File "Base.so" in OpenKE only work in linux. You can install wsl on win10 to build a linux environment and run this project in wsl.
