### ISSUE TITLE
Issue try running the code

### ISSUE THREAD

**Issue by yuhaozhang97** [daiquocnguyen/ConvKB#2]
Hi there,

When I tried running "python train.py --embedding_dim 100 --num_filters 50 --learning_rate 0.000005 --name FB15k-237 --useConstantInit --model_name fb15k237", It seems the program does not create a new "runs" directory. Do you guys know why?

**Comment by daiquocnguyen** [comment]
You should use "--run_folder" to specify the path to the training folder.

**Comment by lileilai** [comment]
Hi,
I read your paper published in AAAI18, i notice that the performance of TransE is  below:
WN18 RR:  3384 0.226 50.1    FB15K-237    347 0.294 46.5
But, i can not  generate this result by the existing open-source code 
Could you mind share your TransE model.
Thank you ~~~

**Comment by daiquocnguyen** [comment]
As mentioned in our paper, I employed a TransE implementation available at: https://github.com/datquocnguyen/STransE .
