### ISSUE TITLE
Interpretability of results/test

### ISSUE THREAD

**Issue by simoneliasen** [daiquocnguyen/ConvKB#20]
Hi, appreciate your work on knowledge graphs!

After running the code (in PyTorch) I do not get a h@10, MR or MRR.
Am I interpreting the results of wrongly, or are they not printed?

Best regards

![image](https://user-images.githubusercontent.com/26206380/193477912-4739a4de-d5ad-46f7-b21c-8d593fda5333.png)

**Comment by daiquocnguyen** [comment]
The output shown in the attached image is correct. It is printed in the line starting with "averaged(filter)" for an order: MRR, MR, H10, H3, H1.

**Comment by simoneliasen** [comment]
@daiquocnguyen Thank you so much for the quick response. I can not find the statement that prints the scores, so I can not make a pull request suggesting changes that write out the names of the metrics (as the order of metrics is not inherently intuitive). Would it be possible to add this to the code?

**Comment by daiquocnguyen** [comment]
I based on the [OpenKE](https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch(old)) framework. You can find Lines 204-210 in `ConvKB_pytorch/base/Test.h`.
